apiVersion: v1
items:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: 2018-11-15T12:26:13Z
    labels:
      app: catalogue
      stage: dev
    name: catalogue
    namespace: mro-catalogue
    resourceVersion: "4784945"
    selfLink: /apis/build.openshift.io/v1/namespaces/mro-catalogue/buildconfigs/catalogue
    uid: a430f762-e8d1-11e8-a280-005056b35471
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: catalogue:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        ref: master
        uri: https://github.com/microservices-cicd/catalogue
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: golang:1.7
      type: Docker
    successfulBuildsHistoryLimit: 5
    triggers:
    - github:
        secret: yqWUMfZaDOtY1MGQPwIG
      type: GitHub
    - generic:
        secret: zNxPZ_AbqZQ-H_eafmd4
      type: Generic
    - type: ConfigChange
    - imageChange:
        lastTriggeredImageID: golang@sha256:93b2b52f1212e97b6650bde1f20f6a359b08c117c57a848970d615fe88623a3d
      type: ImageChange
  status:
    lastVersion: 1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
